ecommerce_analytics:
  outputs:
    dev:
      dbname: postgres_db
      host: localhost
      password: postgres_password
      port: 5430
      schema: dbt_analytics
      threads: 4
      type: postgres
      user: postgres_user
  target: dev
